Ensono/stacks-terraform

google/modules/google-gke/main.tf
Provision GKE nodes in the private subnetwork when the `is_cluster_private` variable is true.
Currently, the `is_cluster_private` variable will provision nodes in the public subnetworks without public IP addresses. 
=> fix: use private subnet for private cluster nodes

google/modules/google-gke/main.tf, google/modules/google-gke/vars.tf
Add variables for gke node type and node count
It was hardcoded to use `n1-standard-1` instances with a maximum of 5 instances
added some terraform variables
=> feat(gke): add variables for gke node type and node count

aws/modules/infrastructure_modules/eks/eks-cluster.tf
Stacks-4684: Add IAM role to pull and push images from ECR
Allow the cluster to pull application images while deployment.
Add IAM Role arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryPowerUser
=> update(eks-worker-iam): add iam roles to pull and push images from ecr

azurerm/modules/azurerm-aks/examples/entire-infra/main.tf, azurerm/modules/azurerm-aks/vars.tf, azurerm/modules/azurerm-app-gateway/examples/appgateway-entire/vars.tf, azurerm/modules/azurerm-app-gateway/examples/appgateway/main.tf, google/modules/google-gke/vars.tf
Upgrade AKS to 1.24.6 and GKE to 1.23.12-gke.100
Existing versions are no longer supported.
https://learn.microsoft.com/en-us/azure/aks/supported-kubernetes-versions?tabs=azure-cli
https://cloud.google.com/kubernetes-engine/docs/release-schedule
=> Upgrade AKS and GKE to supported versions

azurerm/modules/azurerm-adf/providers.tf
Remove provider from adf module
removed because it's not needed, causing unnecessary warning 
deleted provider.tf 
=> fix: removed provider from adf module

azurerm/modules/azurerm-adls/main.tf, azurerm/modules/azurerm-adls/vars.tf, azurerm/modules/azurerm-hub-spoke/locals.tf, azurerm/modules/azurerm-hub-spoke/main.tf, azurerm/modules/azurerm-hub-spoke/vars.tf, azurerm/modules/azurerm-sql/main.tf, azurerm/modules/azurerm-sql/vars.tf
Work can be carried out for the secure data platform work.
=> feat: Update ADLS module for Private Networks

.gitignore, azurerm/modules/azurerm-sql/main.tf, azurerm/modules/azurerm-sql/vars.tf, azurerm/modules/azurerm-vmss/README.md, azurerm/modules/azurerm-vmss/ci_cd_tool_install.sh, azurerm/modules/azurerm-vmss/constraints.tf, azurerm/modules/azurerm-vmss/example/constraints.tf, azurerm/modules/azurerm-vmss/example/main.tf, azurerm/modules/azurerm-vmss/example/providers.tf, azurerm/modules/azurerm-vmss/example/vars.tf, azurerm/modules/azurerm-vmss/main.tf, azurerm/modules/azurerm-vmss/output.tf, azurerm/modules/azurerm-vmss/vars.tf
Allows a VMSS to be created which can be used as a build agent.
=> feat: add initial vmss build agent

azurerm/modules/azurerm-sql/output.tf
=> fixed: output

azurerm/modules/azurerm-adf/constraints.tf
=> fixed provider

azurerm/modules/azurerm-vmss/ci_cd_tool_install.sh
feat: add tools to build agent
=> feat: add tools to build agent

azurerm/modules/azurerm-vmss/main.tf
feat: add build agent extension
=> feat: add build agent extension

azurerm/modules/azurerm-sql/README.md, azurerm/modules/azurerm-sql/main.tf, azurerm/modules/azurerm-sql/vars.tf
=> feat: added pe

azurerm/modules/azurerm-vmss/ci_cd_tool_install.sh
Updated tools for installation for azurem-vmss
Tool required for running DE pipeline
updated ci_cd_tool_install.sh
=> updated tools for installation for azurem-vmss

azurerm/modules/azurerm-vmss/ci_cd_tool_install.sh, azurerm/modules/azurerm-vmss/main.tf, azurerm/modules/azurerm-vmss/vars.tf
=> Feat add docker

azurerm/modules/azurerm-sql/example/main.tf, azurerm/modules/azurerm-sql/example/providers.tf, azurerm/modules/azurerm-sql/main.tf, azurerm/modules/azurerm-sql/vars.tf
Added a value to either enable of disallow public access on SQL module
we need to block all access to SQL module
added a variable to control public access 
=> feat: added disable public access

azurerm/modules/azurerm-adls/data.tf, azurerm/modules/azurerm-adls/example/data.tf, azurerm/modules/azurerm-adls/example/main.tf, azurerm/modules/azurerm-adls/example/providers.tf, azurerm/modules/azurerm-adls/main.tf, azurerm/modules/azurerm-adls/vars.tf, azurerm/modules/azurerm-hub-spoke/example/providers.tf, azurerm/modules/azurerm-kv/data.tf, azurerm/modules/azurerm-kv/example/data.tf, azurerm/modules/azurerm-kv/example/main.tf, azurerm/modules/azurerm-kv/example/providers.tf, azurerm/modules/azurerm-kv/main.tf, azurerm/modules/azurerm-kv/vars.tf, azurerm/modules/azurerm-sql/data.tf, azurerm/modules/azurerm-sql/example/data.tf, azurerm/modules/azurerm-sql/example/main.tf, azurerm/modules/azurerm-sql/example/providers.tf, azurerm/modules/azurerm-sql/main.tf, azurerm/modules/azurerm-sql/vars.tf
Added private DNS zone for different services 
private DNS zone is required for different module in hub network 
=> Feat added pvt dns kv

azurerm/modules/azurerm-hub-spoke/dns.tf, azurerm/modules/azurerm-hub-spoke/vars.tf
=>  updated for unlink

azurerm/modules/azurerm-adf/main.tf, azurerm/modules/azurerm-observability/example/main.tf
=> feat: add explicit depends on for adf ir

azurerm/modules/azurerm-adf/main.tf, azurerm/modules/azurerm-adf/vars.tf
=> feat: paramatise integrated runtime test

azurerm/modules/azurerm-adf/main.tf, azurerm/modules/azurerm-adf/vars.tf
=> feat: update ir authoring var name

azurerm/modules/azurerm-adls/vars.tf, azurerm/modules/azurerm-observability/data.tf, azurerm/modules/azurerm-observability/main.tf
[
](feat: remove data source from observability module)
=> feat: remove data source from observability module

azurerm/modules/azurerm-kv/data.tf, azurerm/modules/azurerm-kv/main.tf, azurerm/modules/azurerm-kv/vars.tf
=> feat: remove data source from kv module

azurerm/modules/azurerm-adb/network.tf, azurerm/modules/azurerm-adls/main.tf, azurerm/modules/azurerm-adls/vars.tf
=> feat: add ignore tags

azurerm/modules/azurerm-kv/data.tf, azurerm/modules/azurerm-kv/main.tf, azurerm/modules/azurerm-kv/vars.tf
=> feat: update kv module

azurerm/modules/azurerm-kv/main.tf
=> feat: add ignore tags to kv private endpoint

azurerm/modules/azurerm-observability/output.tf
=> feat: update output of app insights id

azurerm/modules/azurerm-adb/main.tf
Update dynamic block
Depreciated
=> feat: update adb module

azurerm/modules/azurerm-observability/output.tf
=> feat: output log analytics name

.github/CONTRIBUTING.md, .github/ISSUE-TRIAGE.md, azurerm/modules/azurerm-aks/examples/entire-infra/main.tf, azurerm/modules/azurerm-server-side-app/main.tf
update github amido to ensono references
=> update amido to ensono references

build/azdo/azuredevops-runner.yml
Update pipeline to reference master not main branch
Otherwise pipeline doesn't run
=> Update pipeline to reference master not main branch

aws/modules/infrastructure_modules/vpc/outputs.tf
add private_route_table_ids as output to vpc module
Needed to add extra routes
=> add private_route_table_ids as output to vpc module

aws/modules/infrastructure_modules/eks/eks-cluster.tf, aws/modules/infrastructure_modules/eks/variables.tf
add cluster_security_group_additional_rules variable
Allows the caller to override the rules if needed
=> add cluster_security_group_additional_rules

aws/modules/infrastructure_modules/eks/README.md, aws/modules/infrastructure_modules/vpc/README.md
Updated readme for EKS and VPC modules
Used terradocs to generate readme
=> Updated readme for EKS and VPC modules

aws/modules/infrastructure_modules/eks/outputs.tf
Output Cluster ARN  to facilitate  kube-bench configuration
This is required as input in the Configmap  resource for kube-bench 
Via terraform output
<snip>
Running terraform plan / terraform output  will show the new  output
=> feat: add cluster arn

azurerm/modules/azurerm-server-side-app/locals.tf, azurerm/modules/azurerm-server-side-app/variables.tf
Adds a conditional variable for creating a resource group.
So a variable can be set to force creating a resource group if required.
=> chore: add conditional variable for creating resource group

azurerm/modules/azurerm-server-side-app/main.tf, azurerm/modules/azurerm-server-side-app/versions.tf
update azurerm provider for azurerm-server-side-app to version 4
we want to be using the latest azurerm provider when we can
updated dotnet stack project to use version 4 which uses this module
=> update azurerm provider for azurerm-server-side-app to version 4

aws/modules/infrastructure_modules/vpc/outputs.tf
Exposes all Subnet IDs and CIDR Blocks for external consumption
=> fix: exposes all subnet ids and cidr blocks

aws/modules/infrastructure_modules/vpc/README.md, aws/modules/infrastructure_modules/vpc/examples/basic/main.tf, aws/modules/infrastructure_modules/vpc/locals.tf, aws/modules/infrastructure_modules/vpc/vpc.tf, aws/modules/infrastructure_modules/vpc/vpc_routing.tf
* Naming broken when Name tag passed into AWS VPC Module
* Firewall Route Tables created even when Firewall is disabled
* Updates README
See above.
=> fix: naming broken when name tag passed in

aws/modules/infrastructure_modules/vpc/vpc_routing.tf
* reinstate route that was mistakenly removed
Need Public Internet Access if Firewall is disabled.
=> fix: reinstate route that was mistakenly removed
