- .github/ISSUE-TRIAGE.md
- .github/ISSUE_TEMPLATE/enhancement-suggestion.md
- .github/PULL_REQUEST_TEMPLATE.md
- azurerm/modules/azurerm-app-gateway/app_gateway.tf
* Re-adds a forwarder for Port 80 to the K8s Cluster
- This allows people to get to the cluster via port 80 which can
then be upgraded to https etc
Currently with the new changes and the removal of the Let's Encrypt route to a blob, we accidentally removed the HTTP listener rule.
```
$ curl http://demo-java-api.demo2.nonprod.amidostacks.com -m 10
curl: (28) Connection timed out after 10002 milliseconds
```
> Re-adds a forwarder for Port 80 to the K8s Cluster

- google/modules/google-gke/main.tf
Add tags to cluster labels.
Tags were currently only being added as labels to the node pool and not the cluster itself.
Using existing variable on the gke-cluster module
I have deployed this successfully on the dr project
deploy cluster using this module, look at gke cluster labels
> fix(gke): pass tags through as cluster labels

- google/modules/google-k8s-server-side-app/main.tf
- google/modules/google-k8s-server-side-app/vars.tf
Added a variable to the `google-k8s-server-side-app` module to allow creation of the app dns record as an apex record.
To enable applications to be hosted at the apex record without a record name.
Added a variable `create_apex_record` which defaults to `false`.
If `create_apex_record` = `true` then the apex record is created (the `dns_record` value will be ignored in this scenario)
if `create_apex_record` =`false` then the `dns_record` value is used as before
> feat(gcp): allow apex dns record

- azurerm/modules/azurerm-aks/network.tf
Sets the SPN as the owner on the resource group.
This is very useful in situations where the SPN for the subscription does not have owner rights. By setting the SPN as the owner on the resource group then all operations on resources within that group are permitted. There can be issues with role assignments on resources that are created due to lack of permissions on the SPN
NB. The SPN must have "User Access Administrator" in Azure AD to allow this role assignment to be made. It is _not_ required of the SPN has owner rights.
By using the `azurem_client_config` data resource Terraform can get the `object_id` of the SPN or user performing the deployment.
After the resource group has been created, the `azurerm_role_assignment` resource is used to set the `object_id` as an "Owner" on the newly …
> feat: Ensure that the SPN has owner rights on the resource group

- azurerm/modules/azurerm-aks/locals.tf
- azurerm/modules/azurerm-aks/network.tf
- azurerm/modules/azurerm-aks/vars.tf
- azurerm/modules/azurerm-app-gateway/certs.tf
- azurerm/modules/azurerm-app-gateway/locals.tf
- azurerm/modules/azurerm-app-gateway/vars.tf
This change allows the use of existing DNS zones for setting up the Azure infrastructure. This is more likely to be the scenario that Stacks is being used in, and if used will prevent the need to rerun the Terraform apply as the DNS will already been configured.
During deployment of the infrastructure the user has the ability to set if the templates should set up the DNS zones that have been stated:
If set to `true` then the zones will be configured but the overall deployment will fail. To successfully complete the domain needs to have the nameservers set on it that have been provided by Azure in the created DNS zone. Only when these changes have been propagated can the deployment be run again.
If set to `false` then the zones will not be created, but the templates will still look for the …
> feat: Support using an existing DNS zone in Azure

- azurerm/modules/azurerm-app-gateway/constraints.tf
Reverts amido/stacks-terraform#17
Nope, turns out Terraform was wrong, *le sigh*.
> Revert "fix: Fix vendor name (wtf, not what docs say)"

- azurerm/modules/azurerm-aks/aks.tf
- azurerm/modules/azurerm-aks/vars.tf
The AKS dashboard add-on is set for deprecation. Use the Kubernetes resource view in the Azure portal (preview) instead.
The Kubernetes dashboard is enabled by default for clusters running a Kubernetes version less than 1.18.
The dashboard add-on will be disabled by default for all new clusters created on Kubernetes 1.18 or greater.
Starting with Kubernetes 1.19 in preview, AKS will no longer support installation of the managed kube-dashboard addon.
Existing clusters with the add-on enabled will not be impacted. Users will continue to be able to manually install the open-source dashboard as user-installed software.
https://docs.microsoft.com/en-us/azure/aks/kubernetes-dashboard#before-you-begin …
> chore: remove kube dashboard config

- azurerm/modules/azurerm-app-gateway/certs.tf
- azurerm/modules/azurerm-app-gateway/vars.tf
Added variable to control if complete propagation is required when creating an SSL certificate using `acme_certificate` Terraform resource.
Have encountered issues where propagation is not occuring in DNS zones, or at least the check for the TXT record is not passing. This seems to be incorrect as a `dig` for the TXT record shows the record.
This setting will allow Stacks to be used in more controlled environments.
Added a new variable called `disable_complete_propagation` which is set to false (the default value for the resource) and added the parameter to the `acme_certificate` resoucre.
This variable can now be specified as part of the module parameters to control if propagation is required.
Certificates are now being crreated properly.
Notes on how a reviewer can test the changes, …
> Added ability to disable propagation

- aws/modules/infrastructure_modules/stacks_app/app.tf
- aws/modules/infrastructure_modules/stacks_app/example/main.tf
- aws/modules/infrastructure_modules/stacks_app/variables.tf
Modified dynamodb enable flag variable type to bool, and move the conditional module creation logic to infrastructure side module library rather than calling module.
To abstract the conditional module creation logic to infrastructure side module library
> fix: update enable flag type

- aws/modules/infrastructure_modules/stacks_app/README.md
- aws/modules/infrastructure_modules/stacks_app/app.tf
- aws/modules/infrastructure_modules/stacks_app/example/README.md
- aws/modules/infrastructure_modules/stacks_app/example/main.tf
- aws/modules/infrastructure_modules/stacks_app/example/outputs.tf
- aws/modules/infrastructure_modules/stacks_app/example/terraform.tfvars
- aws/modules/infrastructure_modules/stacks_app/outputs.tf
- aws/modules/infrastructure_modules/stacks_app/variables.tf
- aws/modules/resource_modules/application_integration/sqs/main.tf
- aws/modules/resource_modules/application_integration/sqs/outputs.tf
- aws/modules/resource_modules/application_integration/sqs/variables.tf
1) Add sqs as custom resource module compared to calling from https://registry.terraform.io/modules/terraform-aws-modules/sqs/aws/latest/examples/complete, this fixes the required output required from the module
2) Update table-name and queue-name with environment prefix 
Certain output from sqs module is required to for CQRS and CQRS-Events Configuration 
Add SQS Custom resource in sqs-output/aws/modules/resource_modules/application_integration
```
git clone  https://github.com/amido/stacks-terraform.git
cd aws/modules/infrastructure_modules/stacks_app/example
terraform init
terraform plan -out tfpan
terraform apply 
```
> feat(sqs): add sqs as custom resource module

- azurerm/modules/azurerm-adf/README.md
- azurerm/modules/azurerm-adf/example/providers.tf
- azurerm/modules/azurerm-adf/main.tf
- azurerm/modules/azurerm-adf/vars.tf
added Global parameters to ADF
Global Parameters are needed for Data Pipeline
Added Global Parameter resource Block
> Feat: 5959 add global parameter

- azurerm/modules/azurerm-kv/README.md
- azurerm/modules/azurerm-kv/main.tf
- azurerm/modules/azurerm-kv/vars.tf
- azurerm/modules/azurerm-sql/main.tf
- azurerm/modules/azurerm-sql/vars.tf
Update properties on KV resource to allow private connections.
Part of the secure data platform work.
> feat: add param for private key vault

- azurerm/modules/azurerm-adf/output.tf
Add output of ADF runtime name.
This will be used in with linked services.
> feat: add ADF runtime output

- azurerm/modules/azurerm-adb/network.tf
- azurerm/modules/azurerm-adf/observability.tf
- azurerm/modules/azurerm-adf/vars.tf
- azurerm/modules/azurerm-adls/observability.tf
- azurerm/modules/azurerm-adls/vars.tf
- azurerm/modules/azurerm-hub-spoke/dns.tf
- azurerm/modules/azurerm-kv/example/main.tf
- azurerm/modules/azurerm-kv/observability.tf
- azurerm/modules/azurerm-kv/vars.tf
- azurerm/modules/azurerm-observability/README.md
- azurerm/modules/azurerm-observability/constraints.tf
- azurerm/modules/azurerm-observability/data.tf
- azurerm/modules/azurerm-observability/example/constraints.tf
- azurerm/modules/azurerm-observability/example/main.tf
- azurerm/modules/azurerm-observability/example/vars.tf
- azurerm/modules/azurerm-observability/main.tf
- azurerm/modules/azurerm-observability/output.tf
- azurerm/modules/azurerm-observability/vars.tf
> feat: log analytics diagnostic settings for adls, kv and adf

- azurerm/modules/azurerm-sql/main.tf
sql servers allows 63 characters
this is inconsistent with stacks data where we allow 63 characters and then it gets stripped to 24 which means it loses the environment value and then we get conflicts with other resources.
updated from 24 to 63
> sql servers allows 63 characters

- azurerm/modules/azurerm-vmss/main.tf
Updated agent version to 3.225.0. 
When the scaleset automatically scales it also upgrades that extension which means when we run the terraform again it reverts it back.
This is just a quick fix because we need to understand why its updating it when auto_upgrade_minor_version is false
Azure updating the agent.
Also this module should really be called azurerm-build-agent-vmss because its creating a build agent and isn't a generic module to create vmss but this is a separate issue.
> update azure build agent version

- .gitignore
- azurerm/modules/azurerm-adls/main.tf
- azurerm/modules/azurerm-kv/main.tf
- build/azdo/agent-config-vars.yml
- build/azdo/azuredevops-runner.yml
- build/azdo/azuredevops-vars.yml
- build/azdo/templates/setup.yml
- build/config/stage_envvars.yml
- build/taskctl/contexts.yaml
- build/taskctl/tasks.yaml
- taskctl.yaml
Created a pipeline that runs when a PR is opened and when merged into main.
For now the pipeline is quite basic and only runs a terraform fmt check. 
Once merged to main, it creates a release with release notes
Added a force_release option so we can create a pre-release from feature branches. 
Also fixed formatting errors
Now we don't need to manually create a release. We can reference specific tags when used in other projects
Using the independent runner Publish-GitHubRelease to create the release package
Created from feature branch:
> Feat/18 - added release process for the terraform modules repo

- azurerm/modules/azurerm-app-gateway/provider.tf
Removed the `provider.tf` from the module dicrectory.
When this is in place the module is seen as lagacy and later versions of Terraform will not download the module.
Removed the `provider.tf` file from source control.
Files are downloaded correctly
> Removed provider from module to prevent legacy detection

- azurerm/modules/azurerm-aks/aks.tf
- azurerm/modules/azurerm-app-gateway/vars.tf
* Ups App Gateway to 2022 security standards
* Removes defunct `min_protocol_versions` as we use `Preset` which defines this
* Fixes Worker Nodes constantly recreating by adding VNET Subnet to it explicitly
> fix: Fixes App Gateway and AKS Additional Nodes

- azurerm/modules/azurerm-aks/constraints.tf
- azurerm/modules/azurerm-app-gateway/vars.tf
* Bumps the minimum TF version to 1.5.1, which is in our images
* Uses Optional around App Gateway SSL policy and adds a note about defunct params when using `Predefined`
> fix: Bumps min TF version and uses optional

- aws/modules/infrastructure_modules/eks/eks-cluster.tf
- aws/modules/infrastructure_modules/eks/variables.tf
Adding EKS node instance tenancy as a variable.
In Pay.UK we need to use dediacted instances for the EKS nodes instead of the default shared instances. So making tenancy as a variable and setting the default value to 'default' which corresponds to shared instances.
> Adding node instance tenancy variable

- aws/modules/infrastructure_modules/vpc/vpc.tf
Fix to avoid creation of 3 EIPs (per AZ for NAT) if we are creating just 1 NAT Gateway.
We dont want to create unnecessary resources in our environments.
Adding a check while creating the aws_eip resource.
> fix extra eip creation logic

- aws/modules/infrastructure_modules/eks/outputs.tf
Expose EKS Cluster ARN 
This variable is required in configuration of various other tools.
Exposed via terraform output.
execute terraform plan and apply
> feat: expose cluster ARN for kube-bench config in customer project

- aws/modules/infrastructure_modules/eks/data.tf
- aws/modules/infrastructure_modules/eks/variables.tf
Update kms encryption policy to pass additional IAM Identities so that we can deploy using cross-account role in pre-production/production environments.
It's recommended to use IAM role to deploy in pre-production/production environments.This improves security posture of the EKS module.
By conditional injecting IAM Identities when required by the root module.
Issue
After deploying the changes we need to re-run the plan form the root terraform module to verify that above issue got resolved.
> feat: Inject additional AWS Identities

- aws/modules/infrastructure_modules/eks/locals.tf
- aws/modules/infrastructure_modules/eks/variables.tf
Exposing the kubelet garbage collection threshold settings via variables
We keep getting Disk Pressure issues on our EKS node due as the pod images take a lot of space. With the default setting kubelet does the garbage collection when disk usage reaches 85% which might be quite high. So we want to reduce this threshold limit.
We might get the kubelet logs from nodes but not sure if we will be able to confirm at what disk percent it triggered garbage collection. We are just hoping after setting the threshold to a lower value to run garbage collection early.
> Exposing kubelet garbage collection threshold via variables

- aws/modules/infrastructure_modules/eks/eks-cluster.tf
- aws/modules/infrastructure_modules/eks/variables.tf
To conditionally inject IAM Identities to the KMS Key that used for secret encryption within the cluster. If no IAM role is passed the KMS Policy has only access to the identity that is used to deploy the infrastructure.
This gives flexibility to use IAM User in lower environment and IAM Role in higher environment to access the cluster encryption key and infrastructure deployment.
There are few gotchas like currently apart from the identity used to deploy the infra nobody has access even to view the KMS key making it difficult to manage, this is fixed in later version of the terraform module (V 20.0.0 )
https://github.com/terraform-aws-modules/terraform-aws-eks/issues/2816
Using conditional statement.
Link to documentation updated with …
> FIX: Update custom KMS Policy to add IAM Identities

- aws/modules/infrastructure_modules/eks/eks-cluster.tf
- aws/modules/infrastructure_modules/eks/outputs.tf
- aws/modules/infrastructure_modules/eks/variables.tf
- build/azdo/azuredevops-runner.yml
Upgrades the module to 20.x which fixes this here: https://github.com/terraform-aws-modules/terraform-aws-eks/pull/3055
```
infra:apply: │ Error: associating EKS Identity Provider Config (ensono-stacks-nonprod-ew2-eks:sts): operation error EKS: AssociateIdentityProviderConfig, https response error StatusCode: 400, RequestID: <redacted>, InvalidParameterException: Incorrect Identity Provider URL configuration. The Identity Provider URL cannot be same as OpenID Connect (OIDC) issuer URL
infra:apply: │
infra:apply: │   with module.amido_stacks_infra.module.eks.aws_eks_identity_provider_config.this["sts"],
infra:apply: │   on .terraform/modules/amido_stacks_infra.eks/main.tf line 453, in resource "aws_eks_identity_provider_config" "this":
infra:apply: │  453: resource …
```
> fix: bumps the EKS module version for Kubernetes >=1.30

- azurerm/modules/azurerm-aks/aks.tf
- azurerm/modules/azurerm-aks/variables.tf
Adds Cluster SKU Tier for the AKS Control Plane
Currently it's automatically set to Free which isn't good for Production Environments, also Azure's capacity for Free clusters is much lower and this can lead to errors.
> feat: Adds AKS Cluster Sku Tier for Control Plane

- aws/modules/infrastructure_modules/eks/data.tf
- aws/modules/infrastructure_modules/eks/eks-cluster.tf
- aws/modules/infrastructure_modules/eks/examples/main.tf
- aws/modules/infrastructure_modules/eks/locals.tf
- aws/modules/infrastructure_modules/eks/variables.tf
Expose the Additional IAM roles for the EKS.
For the CloudWatch add-on to work the cluster needs an additional role, so expose the parameter from the underlying module to allow additional policies to be added.
Use example to spin up a cluster
> feat: Expose the Additional IAM roles for the EKS

- aws/modules/infrastructure_modules/eks_irsa/variables.tf
Make additional policies & SA names optional
They shouldn't be mandatory to pass as not all IRSA roles will have additional policies or SAs to assign
EKS Infra is broken atm because of it: https://github.com/Ensono/stacks-infrastructure-eks/actions/runs/10042624392/job/27753488973?pr=12
> fix: Make additional policies & SA names optional

- aws/modules/infrastructure_modules/stacks_app/app.tf
Update stacks-app to create sqs subscription if the enable_queue flag is set. 
Using the module currently fails when enable_queue is false as it tries to create a subscription for a topic that o
Replace hard-coded value with variable
https://github.com/Ensono/stacks-terraform/blob/master/aws/modules/resource_modules/application_integration/sns/main.tf#L13
> fix: create sqs subscription if queue enabled

- azurerm/modules/azurerm-server-side-app/moved.tf
fixes move block for cosmos module move
I had given the path from the root, not from where the module was, so the move wasn't working
> fix: fixes move

- azurerm/modules/azurerm-app-gateway/app_gateway.tf
- azurerm/modules/azurerm-app-gateway/vars.tf
Updated AppGateway to SKU StandardV2. This meant a priority needed to be added to rules and the Public IP address needed to be set as static with a standard SKU, https://thomasthornton.cloud/2023/12/12/resolving-terraform-error-applicationgatewayinvalidpublicipsku-application-gateway-sku-mismatch-with-public-ip/.
Added pick_host_name_from_backend_http_settings  and host_name variables because we want to set these when deploying Azure Container Apps
Standard SKU is not supported
> Add app gateway SKU variables

- azurerm/modules/azurerm-app-gateway/README.md
- azurerm/modules/azurerm-app-gateway/app_gateway.tf
- azurerm/modules/azurerm-app-gateway/vars.tf
Add the ability to update the probe path and status code for app gateway
For ACA we might not have a /health endpoint and want to use something else
> Add the ability to update the probe path for app gateway

- aws/modules/infrastructure_modules/eks/README.md
- aws/modules/infrastructure_modules/eks/eks-cluster.tf
- aws/modules/infrastructure_modules/eks/variables.tf
Add block device mapping variable to be passed to the eks module
So can override the volumes to attach to the instances. By default the attached OS and container image is unencrypted and set to 20gb and 2gb which you can now override.
Example below is setting the OS and Container image volumes to be encrypted and use gp3.
```
block_device_mappings = {
#OS
xvda = {
device_name = "/dev/xvda"
ebs         = {
volume_size           = 2
volume_type           = "gp3"
iops                  = 3000
throughput            = 150
encrypted             = true
delete_on_termination = true
}
}
#Container Image Layers
xvdb = {
device_name = "/dev/xvdb"
ebs         = {
volume_size           = 20
volume_type           = "gp3"
iops                  = 3000
throughput            = 150
encrypted             = …
```
> Add block device mapping

- aws/modules/infrastructure_modules/container_registry/main.tf
- aws/modules/infrastructure_modules/container_registry/variables.tf
- aws/modules/infrastructure_modules/vpc/variables.tf
* Adds tags to ecr module call, not sure if any resources need tagging but might as well offer it.
The underlying container module takes in tags, so even if no resources we use need it (they might) then it's best to allow them to be passed through.
> feat: adds tags to ecr module call
